# Generated by Django 5.0.6 on 2024-06-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_name_item_itemname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemname',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='item_price',
        ),
    ]
