# Generated by Django 5.0.6 on 2024-06-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_item_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='order_quantity',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='status',
            new_name='order_status',
        ),
    ]
