# Generated by Django 5.0.6 on 2024-06-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_name_member_membername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='membername',
            new_name='member_name',
        ),
    ]
